services:
  postgres:
    image: postgres:16-alpine
    container_name: superbodega-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: superbodega
      POSTGRES_USER: superbodega
      POSTGRES_PASSWORD: superbodega
    ports:
      - "55432:5432"
    volumes:
      - superbodega_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U superbodega -d superbodega"]
      interval: 10s
      timeout: 5s
      retries: 5
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: superbodega-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: superbodega-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  admin-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: SuperBodega.Admin.Api
    container_name: superbodega-admin-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__SuperBodegaDb: Host=postgres;Port=5432;Database=superbodega;Username=superbodega;Password=superbodega
    ports:
      - "5088:8080"

  ecommerce-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT: SuperBodega.Ecommerce.Api
    container_name: superbodega-ecommerce-api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__SuperBodegaDb: Host=postgres;Port=5432;Database=superbodega;Username=superbodega;Password=superbodega
      Kafka__BootstrapServers: kafka:29092
    ports:
      - "5180:8080"

volumes:
  superbodega_postgres_data:
